
<?php include('head.php'); ?>

<body  onload="init('projects')">
<div id="wrapper">
	<?php include('header.php'); ?>
    <div id="body">
    	<div id="content">
		
<A  id=project name=projects></A>
<h2>Research Projects</h2>
<ul>

<div class="callout">
<a href="CHKD.png"><img rel="foaf:img" style="border: 0px solid #333;" alt="Shyam1" width="240" align="left" src="CHKD.png" /></a>
</div>
<div align="left">

<b>CHKD Project:</b>Mobile devices such as smart phones have a number of sensors that can be exploited to solve a number
of problems in health care delivery. In this paper we use accelerometer, gyroscope, and compass
sensors to solve a location tracking problem common to many emergency departments. An emergency
department is not friendly to be visually surveyed, layout consists of many isolated islands, and
workstation layout is not standardized. An automated tool to create spaghetti diagrams of movements
of personnel in a non-intrusive way is the problem we are reporting in this paper. A preliminary
prototype shows very encouraging results of producing paths. We also identify challenges and our
approach to meet them.    
</div>
<br/>
<br/>
<br/>
<br/>
<div class="callout">
<a href="Audio-WiFi.png"><img rel="foaf:img" style="border: 0px solid #333;" alt="Shyam1" width="240" align="right" src="Audio-WiFi.png" /></a>
</div>
<div align="left">

<b>Audio-WiFi Project:</b> Wi-Fi is becoming widely popular network interface for data communication in smart devices. However,
the Wi-Fi network still has several inefficiencies in terms
of high energy consumption, unfairness between co-located
nodes, and bandwidth poor utilization. In this project we like to address these issues of the Wi-Fi network by integrating the
mic/speaker of the smart phones as a parallel communication
channel. Our idea is to propose a novel framework of
communication using mic/speaker in order to develop a more
efficient Wi-Fi network communication for smart devices. The non-interferential
nature with Wi-Fi network and low power consumption is the biggest advantage of using
audio communication channel in parallel with WiFi. On the other hand, slow propagation and low data rate of the acoustic channel are some biggest challenges we are addressing in order to implement the Audio-WiFi framework.     
</div>
<br/>
<br/>




<div class="callout">
<a href="meSDN_arch.png"><img rel="foaf:img" style="border: 0px solid #333;" alt="Shyam1" width="240" align="left" src="meSDN_arch.png" /></a>
</div>
<div align="left">

<b>meSDN:Mobile Extension of SDN</b> Now-a-days large number of mobile devices use numerous apps that access internet through wireless. With such significant amount of traffic growth and variability, it is now necessary to have greater visibility and control over the traffic generated from the client devices, such that we can ensure performance guarantees to multiple types of users on a shared network infrastructure. In a wired infrastructure, network virtualization is a means to deliver such performance guarantees using Software-Defined Networking (SDN) APIs do dynamically coordinate network edges (e.g. routers, switch etc.); we don't need to change the client device behavior because the last hop between the network edge and the wired end device is an isolated full-duplex point-to-point link, e.g., Ethernet. However, this is not the case with wireless LANs (WLAN) as the last hop between the mobile device and the access points is shared medium. Moreover the current WiFi MAC protocol does not allow edge access points (APs) to control client uplink transmissions and their 802.11 quality of service (QoS) settings. Therefore, we argue that the SDN framework needs to be extended to the client devices to realize services such as WLAN virtualization with end-to-end QoS, and we propose a framework called msSDN. We show that meSDN also improves application-awareness and power-efficiency from our prototype on Android phones.     
</div>
<br/>
<br/>
<div class="callout">
<a href="MagnoTri.png"><img rel="foaf:img" style="border: 0px solid #333;" alt="Shyam1" width="440" height="190" align="right" src="MagnoTri.png" /></a>
</div>
<div align="left">
<b>MagnoTricorder:</b> Smart Home is becoming a hot area of research for both academic and industrial researchers. In Smart Home, sensing the status of home devices (e.g., home appliances) is a corner stone for having better control over the home appliances as well as power consumption. In this project we present the design and the evaluation of a framework MagnoTricorder, a system that utilizes the magnetic sensor in smartphones to detect the running devices at home thru a singlepoint sensing. MagnoTricorder leverages the effect of Electro Magnetic Interference (EMI) generated by the AC current in the main power-line at home. This EMI induces a magnetic ﬁeld that highly ﬂuctuates the reading of the magnetic sensor in smartphones. In this project, we utilize this characteristic for detecting and identifying the running devices at home thru the Circuit Breaker Panel.
</div>

<br/><br/><br/>

<div class="callout">
<a href="ParkZoom.png"><img rel="foaf:img" style="border: 0px solid #333;" alt="Shyam1" width="440" height="190" align="left" src="ParkZoom.png" /></a>
</div>
<div align="left">
<b>ParkZoom:</b> Accurate localization in outdoor and indoor spaces
is a challenging task. The widely used GPS is not designed
for high accuracy applications and yields accuracy levels not
sufficient for lane or spot level localization. In addition, errors
from inertial sensors accumulate with time due to integration
drift. We introduce a smartphone based, infrastructure aided
parking localization system called ParkZoom for estimating
(zooming into) the precise parking spot location of a vehicle
during traversal in both indoor and outdoor parking lots.
On the vehicle side, the proposed method utilizes conventional
smartphones for generating and transferring continuous sensor
data, such as accelerometer, gyroscope, and compass readings.
On the infrastructure side, ParkZoom employs statistical
learning of sensor data signatures, pattern classification of
data, constraint propagation and error correction for accurate
parking spot identification. The paper presents experimental
results with the ParkZoom algorithm obtained on real data in
city driving and two parking areas.
</div>

<br/><br/><br/>


<div class="callout">
<a href="EnergySniffer.png"><img rel="foaf:img" style="border: 0px solid #333;" alt="Shyam1"  width="200" height="200" align="right" src="EnergySniffer.png" /></a>
</div>
<b>EnergySniffer:</b> In this project, we propose a simple and flexible energy monitoring system using smart phones. We call our system EnergySniffer in which it exploits various sensors, such as magnetic sensor, light, microphone, temperature, camera, WiFi, in smart phones to detect and monitor operating machines in its vicinity. The advantages of EnergySniffer system can be summarized as follow: First, it monitors energy consumption for each individual machine. Second, it has very low overhead and also no new hardware is needed to install or maintain. Third, very flexible in updating software and deploying new services using the application updating feature of the smart phones' application markets. Using the sensors in smart phones to monitor the energy consumption by machines is an eccentric way to approach the problem. Our final objective is to fuse the data from multiple sensors in phone to build a multi sensing framework to generate a unique fingerprint profile for each machine. Later, we apply a machine learning method using fingerprint profiles to recognize and monitor operating machines. In addition to that, this system will also communicate with the Energy Profile of the identiﬁed machine to finally calculate the actual energy consumption.
<br/><br/><br/><br/>

<!--<li><b>Siemens-ODU iLocate Project:</b>-->

<br/>

</ul>
		
		</div>
        
        <div class="clear"></div>
		<?php include('footer.php'); ?>
    </div>
</div>
</body>
</html>

